name: AbTasty
on: [push]

jobs:
  machine:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Adding env variables
        run: |
          echo '${{ secrets.CI_ENV_VARIABLES }}' > cypress.env.json
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headless: true
