name: AbTasty
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Adding env variables
        run: |
          echo '${{ secrets.CI_ENV_VARIABLES }}' > cypress.env.json
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          parallel: true
          browser: chrome
          headless: true
